http:
  listener:
    host: "0.0.0.0"
    port: "8081"
    path: "/travelOnTipCall/{serviceType}"
    
db:
  host: "sql12.freesqldatabase.com"
  port: "3306"
  user: "sql12600385"
  password: "ejcRjkcj9y"
  database: "sql12600385"